"""The module template, kept out of codegen.py so the C++ stays readable."""

MODULE_TEMPLATE = '''// GENERATED FILE -- do not edit by hand.
//
// A complete wtf fuzzer module, generated by fuzzer/codegen.py from:
//   * an InputSpec   derived by prep/input_struct.py   (edge 12)
//   * a HarnessSpec  derived by prep/harness_derive.py (section 3.1's harness box)
//
// Both were derived from Ghidra pseudo-C by an LLM. Regenerate with:
//
//     python -m fuzzer.codegen --spec {spec_path} --harness {harness_path} \\
//         --module-out <this file>
//
// Target : {entry_symbol}
// Input  : {input_param}{size_note}
// Source : {source_functions}
//
// The model's reading of the format:
{input_rationale}
//
// The model's reading of how to drive it:
{harness_rationale}
//
// THIS FILE IS NOT THE BUILD LOCATION. .gitignore's `src/wtf/fuzzer_*` would
// silently untrack it there (D-012); fuzzer/build.py copies it in at build time.
//
// Three wtf facts below are load-bearing and were learned from the source, not
// assumed:
//   * InsertTestcase returning false calls std::abort(), so a rejected test-case
//     returns TRUE having done nothing (D-016).
//   * A Crash_t with an empty name is silently dropped by the master (D-018).
//   * GetNewTestcase runs on the MASTER's hot path and must never block (12.1).

#include "backend.h"
#include "crash_detection_umode.h"
#include "mutator.h"
#include "nlohmann/json.hpp"
#include "snapfuzz_resolve.h"
#include "targets.h"
#include "utils.h"

#include <cstdlib>
#include <deque>
#include <filesystem>
#include <fmt/format.h>
#include <string>
#include <system_error>
#include <vector>

namespace {namespace_name} {{

namespace sfs = std::filesystem;
namespace json = nlohmann;

constexpr bool LoggingOn = false;

template <typename... Args_t>
void DebugPrint(const char *Format, const Args_t &...args) {{
  if constexpr (LoggingOn) {{
    fmt::print("{namespace_name}: ");
    fmt::print(Format, args...);
  }}
}}

//
// The symbols this harness hooks. Every one was chosen by the model from the
// target's decompiled code; none is hardcoded here by a human.
//
{symbol_constants}

//
// Page-tail alignment. Writing the structure flush against the end of the page
// puts the guard page immediately after it, so a read past the buffer FAULTS
// instead of quietly succeeding. This is the one cheap compensation available for
// having no ASAN (DECISIONS DEC-001, D-031): it converts a class of out-of-bounds
// reads -- which section 2 lists as undetectable -- into observable access
// violations.
//
constexpr uint64_t kPageSize = 0x1000;
constexpr size_t kMaxInputBytes = {max_input_bytes};

//
// The seed spool the slow-clock sidecar writes and this mutator drains (12.1).
// From the environment because a module cannot see our CLI.
//
constexpr const char *kSpoolEnvVar = "SNAPFUZZ_SEED_SPOOL";

{struct_definition}

//
// JSON is the on-disk corpus format. Fields are named exactly as the model named
// them, so a corpus is readable against the spec that produced this file.
//
inline void to_json(json::json &Json, const {struct_name} &Value) {{
  Json = json::json{{
{to_json_body}
  }};
}}

//
// Optional-with-default rather than at(): nlohmann 3.10.4 has no
// NLOHMANN_DEFINE_TYPE_..._WITH_DEFAULT, and at() on a missing key THROWS --
// which InsertTestcase would catch and skip, silently rejecting every corpus
// entry written before a field was added.
//
inline void from_json(const json::json &Json, {struct_name} &Value) {{
{from_json_body}
}}

{sequence_wrapper}

//
// Residual state we own. The packet queue is ours; guest memory and registers are
// wtf's to restore.
//
struct {{
  std::deque<{struct_name}> Inputs;
  CpuState_t Context;

  void RestoreGprs(Backend_t *B) {{
    const auto &C = Context;
    B->Rsp(C.Rsp);
    B->Rip(C.Rip);
    B->Rax(C.Rax);
    B->Rbx(C.Rbx);
    B->Rcx(C.Rcx);
    B->Rdx(C.Rdx);
    B->Rsi(C.Rsi);
    B->Rdi(C.Rdi);
    B->R8(C.R8);
    B->R9(C.R9);
    B->R10(C.R10);
    B->R11(C.R11);
    B->R12(C.R12);
    B->R13(C.R13);
    B->R14(C.R14);
    B->R15(C.R15);
  }}
}} GlobalState;

//
// Bytes on the wire for one structure, as the target will see it.
//
inline size_t WireSizeOf(const {struct_name} &Value) {{
  return {wire_size_expr};
}}

//
// InsertTestcase -- runs on the WORKER.
//
// It does NOT write guest memory here. The test-case is {sequence_wording}, and the
// write happens at the entry breakpoint, which is the only place the target is at
// the state the input belongs to.
//
// RETURN VALUE, from src/wtf/client.cc:102-104:
//     if (!Target.InsertTestcase(...)) {{ print; std::abort(); }}
// `false` KILLS THE WORKER. Every rejection of a malformed input therefore
// returns TRUE having done nothing.
//
bool InsertTestcase(const uint8_t *Buffer, const size_t BufferSize) {{
  GlobalState.Inputs.clear();

  if (Buffer == nullptr || BufferSize == 0) {{
    DebugPrint("empty input, nothing to deliver\\n");
    return true;
  }}

  try {{
    const auto &Root = json::json::parse(Buffer, Buffer + BufferSize);
{parse_body}
  }} catch (const std::exception &E) {{
    DebugPrint("input is not valid JSON ({{}}), skipping\\n", E.what());
    return true;
  }}

{immediate_delivery}
  return true;
}}

//
// Init -- runs on the WORKER, once.
//


//
// ResolveModuleBase and ResolveInputAddress come from snapfuzz_resolve.h. They used to
// be emitted here, which meant the model-written path had no copy of them and each
// generator could get the arithmetic wrong on its own (D-075).
//
using snapfuzz::ResolveInputAddress;
using snapfuzz::ResolveModuleBase;

bool Init(const Options_t &Opts, const CpuState_t &State) {{
  //
  // Resolve the module BEFORE installing anything. Failing here is the difference
  // between an error and a campaign that reports coverage while delivering nothing.
  //
  if (ResolveModuleBase("{entry_module_name}") == 0) {{
    return false;
  }}


  GlobalState.Context = State;

  const Gva_t Rsp = Gva_t(g_Backend->Rsp());
  const Gva_t ReturnAddress = Gva_t(g_Backend->VirtRead8(Rsp));

  //
  // The fuzz entry. Each hit delivers the next structure; an empty queue ends the
  // test-case.
  //
  if (!g_Backend->SetBreakpoint({fuzz_entry_target}, [](Backend_t *Backend) {{
        if (GlobalState.Inputs.empty()) {{
          return Backend->Stop(Ok_t());
        }}

        const auto &Input = GlobalState.Inputs.front();
        const size_t Bytes = WireSizeOf(Input);

        //
        // Too big for one page. Drop it and end the test-case -- a Stop(Ok_t()),
        // not a crash and not an abort.
        //
        if (Bytes >= kPageSize || Bytes > kMaxInputBytes) {{
          GlobalState.Inputs.pop_front();
          DebugPrint("input of {{}} bytes does not fit, bailing\\n", Bytes);
          return Backend->Stop(Ok_t());
        }}

{size_param_write}
        //
        // {input_param} {pointer_wording}. Slide the write to the tail of the page
        // so the guard page sits immediately behind it.
        //
        // Aligned on the bytes actually WRITTEN, not on any reported size: the
        // guard page must sit behind the real data, or an over-reported size would
        // read our own bytes instead of faulting.
        //
{placement}

{write_body}
        GlobalState.Inputs.pop_front();
      }})) {{
    fmt::print("{namespace_name}: failed to SetBreakpoint on {{}}\\n", kFuzzEntry);
    return false;
  }}

  //
  // Back at the caller: restore the GPRs so the next structure is delivered from
  // the same state. The snapshot restore does not cover this, because this loops
  // WITHIN one test-case rather than between test-cases (DECISIONS R2).
  //
  // The address is read from the stack rather than named as a symbol: it is a
  // return site, not a function, so there is nothing for dbgeng to resolve.
  //
  //
  // WHERE THE TEST-CASE ENDS, which decides WHICH BUGS THIS HARNESS CAN SEE.
  //
  // `RestoreGprs` rewinds rip to the snapshot, i.e. back to the fuzz entry. That is how a
  // SEQUENCE gets delivered -- return, rewind, deliver the next structure. It also means
  // the CALLER'S EPILOGUE NEVER RUNS, and on a stack-protected binary the epilogue is
  // where `__security_check_cookie` lives. So a harness that rewinds unconditionally
  // cannot observe any stack-cookie violation, no matter how badly the target overflows.
  //
  // Measured on the second real target, whose planted bug overflows the caller's 32-byte
  // buffer:
  //
  //     rewinding:      good  99 instr / cov 53   overflow 124 instr / cov 78   crash 0
  //     running on:     good 283k instr           overflow  3.3k instr         crash 1
  //
  // Same module, same input, same target. The only difference is whether the epilogue was
  // allowed to execute (D-084).
  //
  // So: rewind ONLY when there is another structure to deliver. On the last one, let
  // execution continue -- the crash oracle, `nt!SwapContext` (a clean Cr3Change stop) or
  // `--limit` will end the test-case. Costlier per case, and the cost buys a bug class.
  //
  if (!g_Backend->SetBreakpoint(ReturnAddress, [](Backend_t *Backend) {{
        if (GlobalState.Inputs.empty()) {{
          DebugPrint("last input delivered; letting the caller's epilogue run\\n");
          return;
        }}
        GlobalState.RestoreGprs(Backend);
        DebugPrint("back at the entry point, ready for the next input\\n");
      }})) {{
    fmt::print("{namespace_name}: failed to SetBreakpoint on the return address\\n");
    return false;
  }}

{simulated_returns}
  //
  // THE CRASH ORACLE. wtf infers nothing (section 13.7) -- this installs the
  // platform's user-mode fault hooks (nt!KeBugCheck2, ntdll!RtlDispatchException,
  // verifier!VerifierStopMessage, ...). Each produces a NAMED Crash_t, which
  // matters: the master silently discards a crash whose name is empty
  // (server.h:861-866, D-018).
  //
  // Not derived, and it does not need to be: these fault sites are the same for
  // every Windows target.
  //
  if (!SetupUsermodeCrashDetectionHooks()) {{
    fmt::print("{namespace_name}: failed to SetupUsermodeCrashDetectionHooks\\n");
    return false;
  }}

  return true;
}}

//
// Per-iteration reset. {restore_wording}
//
bool Restore() {{ return true; }}

//
// The mutator -- runs on the MASTER (12.1, edge 21a).
//
// If this is not registered the master silently falls back to a built-in mutator
// and every LLM seed is ignored while coverage keeps climbing.
//
class CustomMutator_t : public Mutator_t {{
  std::unique_ptr<uint8_t[]> ScratchBuffer__;
  span_u8 ScratchBuffer_;
  size_t TestcaseMaxSize_ = 0;
  std::mt19937_64 &Rng_;
  sfs::path SpoolPath_;
  uint64_t SpoolServed_ = 0;

public:
  //
  // CP10's baseline arms select a BUILT-IN mutator here. wtf has no --mutator
  // flag, so the only way to measure ours against its own is for this factory to
  // hand one back when asked.
  //
  static std::unique_ptr<Mutator_t> Create(std::mt19937_64 &Rng,
                                           const size_t TestcaseMaxSize) {{
    if (const char *Env = std::getenv("SNAPFUZZ_MUTATOR"); Env && *Env) {{
      const std::string Which(Env);
      if (Which == "libfuzzer") {{
        fmt::print("{namespace_name}: BASELINE arm -- libfuzzer mutator\\n");
        return LibfuzzerMutator_t::Create(Rng, TestcaseMaxSize);
      }}
      if (Which == "honggfuzz") {{
        fmt::print("{namespace_name}: BASELINE arm -- honggfuzz mutator\\n");
        return HonggfuzzMutator_t::Create(Rng, TestcaseMaxSize);
      }}
      if (Which != "custom") {{
        fmt::print("{namespace_name}: SNAPFUZZ_MUTATOR={{}} is not "
                   "libfuzzer/honggfuzz/custom; refusing to guess the arm\\n",
                   Which);
        std::fflush(stdout);
        std::abort();
      }}
    }}
    return std::make_unique<CustomMutator_t>(Rng, TestcaseMaxSize);
  }}

  explicit CustomMutator_t(std::mt19937_64 &Rng, const size_t TestcaseMaxSize)
      : Rng_(Rng), TestcaseMaxSize_(TestcaseMaxSize) {{
    ScratchBuffer__ = std::make_unique<uint8_t[]>(_1MB);
    ScratchBuffer_ = {{ScratchBuffer__.get(), _1MB}};
    if (const char *Env = std::getenv(kSpoolEnvVar); Env && *Env) {{
      SpoolPath_ = sfs::path(Env);
    }}
  }}

  std::string GetNewTestcase(const Corpus_t &Corpus) override {{
    if (auto Seed = TryTakeSpooledSeed(); Seed.has_value()) {{
      SpoolServed_++;
      DebugPrint("served LLM seed #{{}}\\n", SpoolServed_);
      return std::move(*Seed);
    }}

    if (GetUint32(1, 5) == 5) {{
      return Generate();
    }}

    const Testcase_t *Testcase = Corpus.PickTestcase();
    if (!Testcase) {{
      return Generate();
    }}

    memcpy(ScratchBuffer_.data(), Testcase->Buffer_.get(), Testcase->BufferSize_);
    return Mutate(ScratchBuffer_.data(), Testcase->BufferSize_,
                  ScratchBuffer_.size_bytes());
  }}

private:
  //
  // Take at most ONE seed from the spool and delete it.
  //
  // Ownership (RULE 4, DECISIONS R9): the CONSUMER deletes. The sidecar writes
  // atomically (temp then rename) so a half-written seed is never visible, and
  // this end removes the file once it has the bytes. A file that vanishes between
  // listing and reading is another process winning the race, which is fine -- fall
  // through to the built-in mutator this iteration.
  //
  // MUST NOT BLOCK: this runs per test-case on the master with every worker
  // waiting (12.1).
  //
  std::optional<std::string> TryTakeSpooledSeed() {{
    if (SpoolPath_.empty()) {{
      return std::nullopt;
    }}
    std::error_code Ec;
    sfs::directory_iterator It(SpoolPath_, Ec);
    if (Ec) {{
      return std::nullopt;
    }}
    for (const auto &Entry : It) {{
      if (!Entry.is_regular_file(Ec) || Ec) {{
        continue;
      }}
      const auto &Path = Entry.path();
      if (Path.extension() == ".tmp") {{
        continue;
      }}
      std::string Content;
      if (!ReadWholeFile(Path, Content)) {{
        continue;
      }}
      sfs::remove(Path, Ec);
      return Content;
    }}
    return std::nullopt;
  }}

  static bool ReadWholeFile(const sfs::path &Path, std::string &Out) {{
    FILE *File = nullptr;
    if (fopen_s(&File, Path.string().c_str(), "rb") != 0 || File == nullptr) {{
      return false;
    }}
    char Buffer[4096];
    size_t Read = 0;
    Out.clear();
    while ((Read = fread(Buffer, 1, sizeof(Buffer), File)) > 0) {{
      Out.append(Buffer, Read);
    }}
    fclose(File);
    return !Out.empty();
  }}

  uint32_t GetUint32(const uint32_t Min, const uint32_t Max) {{
    return Min + uint32_t(Rng_() % (uint64_t(Max) - Min + 1));
  }}

  //
  // Generate from scratch, field by field, per the derived spec.
  //
  // Length fields are made CONSISTENT here: an input whose length disagrees with
  // its payload is rejected at the parser's first check, and a corpus of rejected
  // inputs teaches the fuzzer nothing (CP4). Mutate is where they are allowed to
  // disagree, because that disagreement is the bug.
  //
  std::string Generate() {{
{generate_body}
  }}

  std::string Mutate(uint8_t *Data, const size_t DataLen, const size_t MaxSize) {{
{mutate_body}
  }}
}};

}} // namespace {namespace_name}

//
// The registration. ONE artifact, loaded by the master (which uses
// CustomMutator_t) and every worker (which uses Init / InsertTestcase / Restore).
// Both roles, one module (edges 21a and 21b).
//
Target_t {target_var}("{target_name}", {namespace_name}::Init,
                      {namespace_name}::InsertTestcase, {namespace_name}::Restore,
                      {namespace_name}::CustomMutator_t::Create);
'''
