// GENERATED FILE -- do not edit by hand.
//
// A complete wtf fuzzer module, generated by fuzzer/codegen.py from:
//   * an InputSpec   derived by prep/input_struct.py   (edge 12)
//   * a HarnessSpec  derived by prep/harness_derive.py (section 3.1's harness box)
//
// Both were derived from Ghidra pseudo-C by an LLM. Regenerate with:
//
//     python -m fuzzer.codegen --spec artifacts\input_spec.json --harness artifacts\harness_spec.json \
//         --module-out <this file>
//
// Target : tlv_server!ProcessPacket
// Input  : rcx, length in rdx
// Source : ProcessPacket, main
//
// The model's reading of the format:
//   The packet format begins with a 4-byte command (offset 0), a 2-byte header field (offset 4), and a 2-byte payload length (offset 6). The payload starts at offset 8 and its size is given by the length field. The caller supplies the total packet size, but the parser only uses the fields described.
//
// The model's reading of how to drive it:
//   Input arrives via main's recv loop: it reads a 4-byte length, allocates a buffer, reads exactly that many bytes, then calls ProcessPacket(buf, len). Each call processes one TLV structure (command + ID + length + payload), so deliver_sequence=true. The snapshot restore already resets all globals (ChunkList, TLS), so restore_globals is empty. printf is silenced because it's pure logging. No end_of_testcase breakpoint needed because returning from ProcessPacket naturally ends one test case. Max input bounded by main's 0x1000 check, well under 4096.
//
// THIS FILE IS NOT THE BUILD LOCATION. .gitignore's `src/wtf/fuzzer_*` would
// silently untrack it there (D-012); fuzzer/build.py copies it in at build time.
//
// Three wtf facts below are load-bearing and were learned from the source, not
// assumed:
//   * InsertTestcase returning false calls std::abort(), so a rejected test-case
//     returns TRUE having done nothing (D-016).
//   * A Crash_t with an empty name is silently dropped by the master (D-018).
//   * GetNewTestcase runs on the MASTER's hot path and must never block (12.1).

#include "backend.h"
#include "crash_detection_umode.h"
#include "mutator.h"
#include "nlohmann/json.hpp"
#include "targets.h"
#include "utils.h"

#include <cstdlib>
#include <deque>
#include <filesystem>
#include <fmt/format.h>
#include <string>
#include <system_error>
#include <vector>

namespace GenTlv {

namespace sfs = std::filesystem;
namespace json = nlohmann;

constexpr bool LoggingOn = false;

template <typename... Args_t>
void DebugPrint(const char *Format, const Args_t &...args) {
  if constexpr (LoggingOn) {
    fmt::print("GenTlv: ");
    fmt::print(Format, args...);
  }
}

//
// The symbols this harness hooks. Every one was chosen by the model from the
// target's decompiled code; none is hardcoded here by a human.
//
constexpr const char *kFuzzEntry = "tlv_server!ProcessPacket";
constexpr const char *kSkip01 = "tlv_server!printf";  // silence_io: All printf calls are diagnostic logging (e.g., 'Allocate command', 'Edit command', error m

//
// Page-tail alignment. Writing the structure flush against the end of the page
// puts the guard page immediately after it, so a read past the buffer FAULTS
// instead of quietly succeeding. This is the one cheap compensation available for
// having no ASAN (DECISIONS DEC-001, D-031): it converts a class of out-of-bounds
// reads -- which section 2 lists as undetectable -- into observable access
// violations.
//
constexpr uint64_t kPageSize = 0x1000;
constexpr size_t kMaxInputBytes = 4096;

//
// The seed spool the slow-clock sidecar writes and this mutator drains (12.1).
// From the environment because a module cannot see our CLI.
//
constexpr const char *kSpoolEnvVar = "SNAPFUZZ_SEED_SPOOL";

struct Packet_t {
  // scalar -- iVar2 = *(int *)param_1; // command ID at offset 0
  uint32_t Cmd;
  // scalar -- *(undefined2 *)(param_1 + 4) // stored into local_res8 at offset 4
  uint16_t HeaderInfo;
  // length; counts Payload in bytes -- (ulonglong)*(ushort *)((longlong)local_res8._Mypair._Myval2 + 2) // length of payload used for memcpy
  uint16_t PayloadSize;
  // bytes; capped at 65535 bytes -- memcpy(*(void **)_Var1._Myval2, param_1 + 8, (ulonglong)*(ushort *)((longlong)local_res8._Mypair._Myval2 + 2)); // copies PayloadSize bytes from offset 8
  std::vector<uint8_t> Payload;

  //
  // How many bytes the target is TOLD arrived, independent of how many were
  // written. 0 means the natural size.
  //
  // Without this a guard like `if (size < header) reject` is unreachable BY
  // CONSTRUCTION -- no seed can satisfy it, however well reasoned. CP7 measured
  // exactly that: the frontier offered the branch, the model aimed at it
  // correctly, and nothing could have worked (D-040). It is also realistic: a
  // peer on a socket can send fewer bytes than its header claims.
  //
  uint32_t WireSize = 0;
};

//
// JSON is the on-disk corpus format. Fields are named exactly as the model named
// them, so a corpus is readable against the spec that produced this file.
//
inline void to_json(json::json &Json, const Packet_t &Value) {
  Json = json::json{
      {"Cmd", Value.Cmd},
      {"HeaderInfo", Value.HeaderInfo},
      {"PayloadSize", Value.PayloadSize},
      {"Payload", Value.Payload},
      {"WireSize", Value.WireSize}
  };
}

//
// Optional-with-default rather than at(): nlohmann 3.10.4 has no
// NLOHMANN_DEFINE_TYPE_..._WITH_DEFAULT, and at() on a missing key THROWS --
// which InsertTestcase would catch and skip, silently rejecting every corpus
// entry written before a field was added.
//
inline void from_json(const json::json &Json, Packet_t &Value) {
  Value.Cmd = Json.value("Cmd", uint32_t(0));
  Value.HeaderInfo = Json.value("HeaderInfo", uint16_t(0));
  Value.PayloadSize = Json.value("PayloadSize", uint16_t(0));
  Value.Payload = Json.value("Payload", std::vector<uint8_t>{});
  Value.WireSize = Json.value("WireSize", uint32_t(0));
}

//
// One test-case carries several structures, delivered in order to the
// SAME live process. State the target builds up persists between them,
// which is what makes a branch requiring an existing object reachable
// at all (section 13.7).
//
struct Packets_t {
  std::vector<Packet_t> Packets;
};

inline void from_json(const json::json &Json,
                      Packets_t &Value) {
  Json.at("Packets").get_to(Value.Packets);
}

inline void to_json(json::json &Json,
                    const Packets_t &Value) {
  Json = json::json{{"Packets", Value.Packets}};
}

//
// Residual state we own. The packet queue is ours; guest memory and registers are
// wtf's to restore.
//
struct {
  std::deque<Packet_t> Inputs;
  CpuState_t Context;

  void RestoreGprs(Backend_t *B) {
    const auto &C = Context;
    B->Rsp(C.Rsp);
    B->Rip(C.Rip);
    B->Rax(C.Rax);
    B->Rbx(C.Rbx);
    B->Rcx(C.Rcx);
    B->Rdx(C.Rdx);
    B->Rsi(C.Rsi);
    B->Rdi(C.Rdi);
    B->R8(C.R8);
    B->R9(C.R9);
    B->R10(C.R10);
    B->R11(C.R11);
    B->R12(C.R12);
    B->R13(C.R13);
    B->R14(C.R14);
    B->R15(C.R15);
  }
} GlobalState;

//
// Bytes on the wire for one structure, as the target will see it.
//
inline size_t WireSizeOf(const Packet_t &Value) {
  return 8 + Value.Payload.size();
}

//
// InsertTestcase -- runs on the WORKER.
//
// It does NOT write guest memory here. The test-case is a *sequence* of structures, and the
// write happens at the entry breakpoint, which is the only place the target is at
// the state the input belongs to.
//
// RETURN VALUE, from src/wtf/client.cc:102-104:
//     if (!Target.InsertTestcase(...)) { print; std::abort(); }
// `false` KILLS THE WORKER. Every rejection of a malformed input therefore
// returns TRUE having done nothing.
//
bool InsertTestcase(const uint8_t *Buffer, const size_t BufferSize) {
  GlobalState.Inputs.clear();

  if (Buffer == nullptr || BufferSize == 0) {
    DebugPrint("empty input, nothing to deliver\n");
    return true;
  }

  try {
    const auto &Root = json::json::parse(Buffer, Buffer + BufferSize);
    const auto &Parsed = Root.get<Packets_t>();
    for (auto Item : Parsed.Packets) {
      GlobalState.Inputs.emplace_back(std::move(Item));
    }
  } catch (const std::exception &E) {
    DebugPrint("input is not valid JSON ({}), skipping\n", E.what());
    return true;
  }

  return true;
}

//
// Init -- runs on the WORKER, once.
//
bool Init(const Options_t &Opts, const CpuState_t &State) {
  GlobalState.Context = State;

  const Gva_t Rsp = Gva_t(g_Backend->Rsp());
  const Gva_t ReturnAddress = Gva_t(g_Backend->VirtRead8(Rsp));

  //
  // The fuzz entry. Each hit delivers the next structure; an empty queue ends the
  // test-case.
  //
  if (!g_Backend->SetBreakpoint(kFuzzEntry, [](Backend_t *Backend) {
        if (GlobalState.Inputs.empty()) {
          return Backend->Stop(Ok_t());
        }

        const auto &Input = GlobalState.Inputs.front();
        const size_t Bytes = WireSizeOf(Input);

        //
        // Too big for one page. Drop it and end the test-case -- a Stop(Ok_t()),
        // not a crash and not an abort.
        //
        if (Bytes >= kPageSize || Bytes > kMaxInputBytes) {
          GlobalState.Inputs.pop_front();
          DebugPrint("input of {} bytes does not fit, bailing\n", Bytes);
          return Backend->Stop(Ok_t());
        }

        //
        // rdx carries the length, in BYTES.
        //
        // WireSize, when set, reports FEWER (or more) bytes than
        // were written -- modelling a short read on a socket. It is
        // what makes a `size < header` guard reachable at all
        // (D-040).
        //
        size_t Reported = Bytes;
        if (Input.WireSize != 0 && Input.WireSize < kPageSize) {
          Reported = Input.WireSize;
        }
        Backend->Rdx(Reported);

        //
        // rcx HOLDS the buffer address. Slide the write to the tail of the page
        // so the guard page sits immediately behind it.
        //
        // Aligned on the bytes actually WRITTEN, not on any reported size: the
        // guard page must sit behind the real data, or an over-reported size would
        // read our own bytes instead of faulting.
        //
        const uint64_t PageBase = Backend->Rcx();
        uint64_t Address = PageBase + (kPageSize - Bytes);
        Backend->Rcx(Address);

        if (!Backend->VirtWriteStructDirty(Gva_t(Address),
                                           &Input.Cmd)) {
          fmt::print("GenTlv: failed to write Cmd\n");
          std::abort();
        }
        Address += sizeof(Input.Cmd);

        if (!Backend->VirtWriteStructDirty(Gva_t(Address),
                                           &Input.HeaderInfo)) {
          fmt::print("GenTlv: failed to write HeaderInfo\n");
          std::abort();
        }
        Address += sizeof(Input.HeaderInfo);

        //
        // Written from the test-case, NOT recomputed from the
        // payload. The disagreement between them is the bug
        // trigger; recomputing here would neuter every overflow.
        //
        if (!Backend->VirtWriteStructDirty(Gva_t(Address),
                                           &Input.PayloadSize)) {
          fmt::print("GenTlv: failed to write PayloadSize\n");
          std::abort();
        }
        Address += sizeof(Input.PayloadSize);

        if (!Input.Payload.empty() &&
            !Backend->VirtWriteDirty(Gva_t(Address),
                                     Input.Payload.data(),
                                     Input.Payload.size())) {
          fmt::print("GenTlv: failed to write Payload\n");
          std::abort();
        }
        GlobalState.Inputs.pop_front();
      })) {
    fmt::print("GenTlv: failed to SetBreakpoint on {}\n", kFuzzEntry);
    return false;
  }

  //
  // Back at the caller: restore the GPRs so the next structure is delivered from
  // the same state. The snapshot restore does not cover this, because this loops
  // WITHIN one test-case rather than between test-cases (DECISIONS R2).
  //
  // The address is read from the stack rather than named as a symbol: it is a
  // return site, not a function, so there is nothing for dbgeng to resolve.
  //
  if (!g_Backend->SetBreakpoint(ReturnAddress, [](Backend_t *Backend) {
        GlobalState.RestoreGprs(Backend);
        DebugPrint("back at the entry point, ready for the next input\n");
      })) {
    fmt::print("GenTlv: failed to SetBreakpoint on the return address\n");
    return false;
  }

  //
  // tlv_server!printf: silence_io.
  // All printf calls are diagnostic logging (e.g., 'Allocate command', 'Edit command', error messages). They do not affect parsing logic or state. Silencing them removes console I/O ov
  //
  if (!g_Backend->SetBreakpoint(kSkip01, [](Backend_t *Backend) {
        Backend->SimulateReturnFromFunction(0);
      })) {
    fmt::print("GenTlv: failed to SetBreakpoint on {}\n", kSkip01);
    return false;
  }

  //
  // THE CRASH ORACLE. wtf infers nothing (section 13.7) -- this installs the
  // platform's user-mode fault hooks (nt!KeBugCheck2, ntdll!RtlDispatchException,
  // verifier!VerifierStopMessage, ...). Each produces a NAMED Crash_t, which
  // matters: the master silently discards a crash whose name is empty
  // (server.h:861-866, D-018).
  //
  // Not derived, and it does not need to be: these fault sites are the same for
  // every Windows target.
  //
  if (!SetupUsermodeCrashDetectionHooks()) {
    fmt::print("GenTlv: failed to SetupUsermodeCrashDetectionHooks\n");
    return false;
  }

  return true;
}

//
// Per-iteration reset. The snapshot restore handles guest memory and registers; the only residual state here is the input queue, which InsertTestcase clears before each test-case. Restoring twice would be as wrong as not restoring, so this is a no-op (DECISIONS R2).
//
bool Restore() { return true; }

//
// The mutator -- runs on the MASTER (12.1, edge 21a).
//
// If this is not registered the master silently falls back to a built-in mutator
// and every LLM seed is ignored while coverage keeps climbing.
//
class CustomMutator_t : public Mutator_t {
  std::unique_ptr<uint8_t[]> ScratchBuffer__;
  span_u8 ScratchBuffer_;
  size_t TestcaseMaxSize_ = 0;
  std::mt19937_64 &Rng_;
  sfs::path SpoolPath_;
  uint64_t SpoolServed_ = 0;

public:
  //
  // CP10's baseline arms select a BUILT-IN mutator here. wtf has no --mutator
  // flag, so the only way to measure ours against its own is for this factory to
  // hand one back when asked.
  //
  static std::unique_ptr<Mutator_t> Create(std::mt19937_64 &Rng,
                                           const size_t TestcaseMaxSize) {
    if (const char *Env = std::getenv("SNAPFUZZ_MUTATOR"); Env && *Env) {
      const std::string Which(Env);
      if (Which == "libfuzzer") {
        fmt::print("GenTlv: BASELINE arm -- libfuzzer mutator\n");
        return LibfuzzerMutator_t::Create(Rng, TestcaseMaxSize);
      }
      if (Which == "honggfuzz") {
        fmt::print("GenTlv: BASELINE arm -- honggfuzz mutator\n");
        return HonggfuzzMutator_t::Create(Rng, TestcaseMaxSize);
      }
      if (Which != "custom") {
        fmt::print("GenTlv: SNAPFUZZ_MUTATOR={} is not "
                   "libfuzzer/honggfuzz/custom; refusing to guess the arm\n",
                   Which);
        std::fflush(stdout);
        std::abort();
      }
    }
    return std::make_unique<CustomMutator_t>(Rng, TestcaseMaxSize);
  }

  explicit CustomMutator_t(std::mt19937_64 &Rng, const size_t TestcaseMaxSize)
      : Rng_(Rng), TestcaseMaxSize_(TestcaseMaxSize) {
    ScratchBuffer__ = std::make_unique<uint8_t[]>(_1MB);
    ScratchBuffer_ = {ScratchBuffer__.get(), _1MB};
    if (const char *Env = std::getenv(kSpoolEnvVar); Env && *Env) {
      SpoolPath_ = sfs::path(Env);
    }
  }

  std::string GetNewTestcase(const Corpus_t &Corpus) override {
    if (auto Seed = TryTakeSpooledSeed(); Seed.has_value()) {
      SpoolServed_++;
      DebugPrint("served LLM seed #{}\n", SpoolServed_);
      return std::move(*Seed);
    }

    if (GetUint32(1, 5) == 5) {
      return Generate();
    }

    const Testcase_t *Testcase = Corpus.PickTestcase();
    if (!Testcase) {
      return Generate();
    }

    memcpy(ScratchBuffer_.data(), Testcase->Buffer_.get(), Testcase->BufferSize_);
    return Mutate(ScratchBuffer_.data(), Testcase->BufferSize_,
                  ScratchBuffer_.size_bytes());
  }

private:
  //
  // Take at most ONE seed from the spool and delete it.
  //
  // Ownership (RULE 4, DECISIONS R9): the CONSUMER deletes. The sidecar writes
  // atomically (temp then rename) so a half-written seed is never visible, and
  // this end removes the file once it has the bytes. A file that vanishes between
  // listing and reading is another process winning the race, which is fine -- fall
  // through to the built-in mutator this iteration.
  //
  // MUST NOT BLOCK: this runs per test-case on the master with every worker
  // waiting (12.1).
  //
  std::optional<std::string> TryTakeSpooledSeed() {
    if (SpoolPath_.empty()) {
      return std::nullopt;
    }
    std::error_code Ec;
    sfs::directory_iterator It(SpoolPath_, Ec);
    if (Ec) {
      return std::nullopt;
    }
    for (const auto &Entry : It) {
      if (!Entry.is_regular_file(Ec) || Ec) {
        continue;
      }
      const auto &Path = Entry.path();
      if (Path.extension() == ".tmp") {
        continue;
      }
      std::string Content;
      if (!ReadWholeFile(Path, Content)) {
        continue;
      }
      sfs::remove(Path, Ec);
      return Content;
    }
    return std::nullopt;
  }

  static bool ReadWholeFile(const sfs::path &Path, std::string &Out) {
    FILE *File = nullptr;
    if (fopen_s(&File, Path.string().c_str(), "rb") != 0 || File == nullptr) {
      return false;
    }
    char Buffer[4096];
    size_t Read = 0;
    Out.clear();
    while ((Read = fread(Buffer, 1, sizeof(Buffer), File)) > 0) {
      Out.append(Buffer, Read);
    }
    fclose(File);
    return !Out.empty();
  }

  uint32_t GetUint32(const uint32_t Min, const uint32_t Max) {
    return Min + uint32_t(Rng_() % (uint64_t(Max) - Min + 1));
  }

  //
  // Generate from scratch, field by field, per the derived spec.
  //
  // Length fields are made CONSISTENT here: an input whose length disagrees with
  // its payload is rejected at the parser's first check, and a corpus of rejected
  // inputs teaches the fuzzer nothing (CP4). Mutate is where they are allowed to
  // disagree, because that disagreement is the bug.
  //
  std::string Generate() {
    Packets_t Root;
    const uint32_t Count = GetUint32(1, 10);
    for (uint32_t N = 0; N < Count; N++) {
      Packet_t Item;
      Item.Cmd = uint32_t(GetUint32(0, 16));
      Item.HeaderInfo = uint16_t(GetUint32(0, 16));
      // Consistent with the payload: an inconsistent length is
      // rejected at the parser's first check, and a corpus of
      // rejected inputs teaches the fuzzer nothing (CP4).
      Item.PayloadSize = uint16_t(Item.Payload.size());
      const uint32_t Len = GetUint32(0, 4088);
      Item.Payload.resize(Len);
      for (uint32_t I = 0; I < Len; I++) {
        Item.Payload[I] = uint8_t(GetUint32(0, 255));
      }
      // Usually the natural size; occasionally a lie, which is the
      // only way a `size < header` guard is reachable (D-040).
      Item.WireSize = GetUint32(1, 8) == 1 ? GetUint32(0, 8) : 0;
      Root.Packets.emplace_back(Item);
    }
    json::json Serialized;
    to_json(Serialized, Root);
    return Serialized.dump();
  }

  std::string Mutate(uint8_t *Data, const size_t DataLen, const size_t MaxSize) {
    Packets_t Root;
    try {
      const auto &Parsed = json::json::parse(Data, Data + DataLen);
      Root = Parsed.get<Packets_t>();
    } catch (const std::exception &) {
      // Not our format -- start fresh rather than aborting the master.
      return Generate();
    }
    if (Root.Packets.empty()) {
      return Generate();
    }

    const size_t Index = GetUint32(0, uint32_t(Root.Packets.size() - 1));
    auto &Item = Root.Packets[Index];

    switch (GetUint32(0, 5)) {
    case 0:
      // Flip a header field. Length fields included ON PURPOSE: a
      // length that disagrees with the payload is the bug.
      switch (GetUint32(0, 2)) {
      case 0:
        Item.Cmd = uint32_t(GetUint32(0, 0xffff));
        break;
      case 1:
        Item.HeaderInfo = uint16_t(GetUint32(0, 0xffff));
        break;
      case 2:
        Item.PayloadSize = uint16_t(GetUint32(0, 0xffff));
        break;
      }
      break;
    case 1: {
      // Grow the payload without touching the declared length.
      const uint32_t Extra = GetUint32(1, 64);
      for (uint32_t I = 0; I < Extra; I++) {
        Item.Payload.push_back(uint8_t(GetUint32(0, 255)));
      }
      break;
    }
    case 2:
      // Shrink it, likewise leaving the length alone.
      if (!Item.Payload.empty()) {
        Item.Payload.resize(Item.Payload.size() / 2);
      }
      break;
    case 3:
      if (!Item.Payload.empty()) {
        Item.Payload[GetUint32(0, uint32_t(Item.Payload.size() - 1))] =
            uint8_t(GetUint32(0, 255));
      }
      break;
    case 4:
      // Duplicate a structure. Repetition is how a fixed-size table
      // gets exhausted, and coverage gives no gradient toward it
      // (eval/coverage_gradient.py).
      if (Root.Packets.size() < 64) {
        Root.Packets.push_back(Item);
      }
      break;
    case 5:
      if (Root.Packets.size() > 1) {
        Root.Packets.erase(Root.Packets.begin() + Index);
      }
      break;
    default:
      Item.WireSize = GetUint32(0, 16);
      break;
    }
    json::json Serialized;
    to_json(Serialized, Root);
    std::string Out = Serialized.dump();
    if (Out.size() > MaxSize) {
      return Generate();
    }
    return Out;
  }
};

} // namespace GenTlv

//
// The registration. ONE artifact, loaded by the master (which uses
// CustomMutator_t) and every worker (which uses Init / InsertTestcase / Restore).
// Both roles, one module (edges 21a and 21b).
//
Target_t GenTlvTarget("snapfuzz_gen", GenTlv::Init,
                      GenTlv::InsertTestcase, GenTlv::Restore,
                      GenTlv::CustomMutator_t::Create);
