// GENERATED FILE -- do not edit by hand.
//
// A complete wtf fuzzer module, generated by fuzzer/codegen.py from:
//   * an InputSpec   derived by prep/input_struct.py   (edge 12)
//   * a HarnessSpec  derived by prep/harness_derive.py (section 3.1's harness box)
//
// Both were derived from Ghidra pseudo-C by an LLM. Regenerate with:
//
//     python -m fuzzer.codegen --spec D:\wtf-llm\artifacts\fuzzing-test-cmp\input_spec.json --harness D:\wtf-llm\artifacts\fuzzing-test-cmp\harness_spec.json \
//         --module-out <this file>
//
// Target : fuzzing-test-cmp!FUN_1400447c0
// Input  : rcx, length in rdx
// Source : FUN_1400447c0, FUN_140044aa0, __CheckForDebuggerJustMyCode, memcmp, thunk_FUN_1400c08f0
//
// The model's reading of the format:
//   The parser expects a 4-byte magic value, followed by a 1-byte length field, then that many bytes of payload. The magic is validated first; if it matches the function proceeds, otherwise it rejects. The length field determines the size of the following payload, which is read as a raw byte array.
//
// The model's reading of how to drive it:
//   The fuzz target FUN_1400447c0 receives a pointer to input in RCX and length in RDX. It checks for a 4-byte magic header (DAT_1400c6174) and if matched, passes the buffer and a length derived from the 5th byte to thunk_FUN_1400c08f0. The caller FUN_140044aa0 allocates a 0x2000-byte heap buffer via VirtualAlloc, writes a test structure with a 5-byte header (0x46,0x55,0x5a,0x5a,0x04) followed by 3 bytes of payload, and calls the entry with length 8. Since the heap buffer size (0x2000) is not encoded in the entry's signature, input_buffer_bytes is left null to use page-end placement. __CheckForDebuggerJustMyCode is silenced to avoid debugger-dependent behavior. No other I/O or nondeterministic calls are evident in the entry; thunk_FUN_1400c08f0 appears to be the core parser and is not silenced. The snapshot restore handles global state, so restore_globals is empty.
//
// THIS FILE IS NOT THE BUILD LOCATION. .gitignore's `src/wtf/fuzzer_*` would
// silently untrack it there (D-012); fuzzer/build.py copies it in at build time.
//
// Three wtf facts below are load-bearing and were learned from the source, not
// assumed:
//   * InsertTestcase returning false calls std::abort(), so a rejected test-case
//     returns TRUE having done nothing (D-016).
//   * A Crash_t with an empty name is silently dropped by the master (D-018).
//   * GetNewTestcase runs on the MASTER's hot path and must never block (12.1).

#include "backend.h"
#include "crash_detection_umode.h"
#include "mutator.h"
#include "nlohmann/json.hpp"
#include "snapfuzz_resolve.h"
#include "targets.h"
#include "utils.h"

#include <cstdlib>
#include <deque>
#include <filesystem>
#include <fmt/format.h>
#include <string>
#include <system_error>
#include <vector>

namespace GenFuzzingTestCmp {

namespace sfs = std::filesystem;
namespace json = nlohmann;

constexpr bool LoggingOn = false;

template <typename... Args_t>
void DebugPrint(const char *Format, const Args_t &...args) {
  if constexpr (LoggingOn) {
    fmt::print("GenFuzzingTestCmp: ");
    fmt::print(Format, args...);
  }
}

//
// The symbols this harness hooks. Every one was chosen by the model from the
// target's decompiled code; none is hardcoded here by a human.
//
constexpr const char *kFuzzEntry = "fuzzing-test-cmp!FUN_1400447c0";
constexpr const char *kSkip01 = "fuzzing-test-cmp!__CheckForDebuggerJustMyCode";  // silence_io: Debugger check that may produce side effects or terminate; safe to stub as no-op with zero

//
// Page-tail alignment. Writing the structure flush against the end of the page
// puts the guard page immediately after it, so a read past the buffer FAULTS
// instead of quietly succeeding. This is the one cheap compensation available for
// having no ASAN (DECISIONS DEC-001, D-031): it converts a class of out-of-bounds
// reads -- which section 2 lists as undetectable -- into observable access
// violations.
//
constexpr uint64_t kPageSize = 0x1000;
constexpr size_t kMaxInputBytes = 4096;

//
// The seed spool the slow-clock sidecar writes and this mutator drains (12.1).
// From the environment because a module cannot see our CLI.
//
constexpr const char *kSpoolEnvVar = "SNAPFUZZ_SEED_SPOOL";

struct FuzzPacket {
  // magic; parser compares against 0x5a5a5546 -- The first 4 bytes at offset 0 are compared with constant 0x5a5a5546 ("FUZZ") via memcmp(param_1,&DAT_1400c6174,4).
  uint32_t magic = 0x5a5a5546;
  // length; counts payload in elements -- Byte at offset 4 (param_1[4]) is read as a length value that tells how many payload bytes follow.
  uint8_t total_len;
  // bytes; capped at 255 bytes -- Variable length data after the length byte; the number of bytes to read is given by the total_len field.
  std::vector<uint8_t> payload;

  //
  // How many bytes the target is TOLD arrived, independent of how many were
  // written. 0 means the natural size.
  //
  // Without this a guard like `if (size < header) reject` is unreachable BY
  // CONSTRUCTION -- no seed can satisfy it, however well reasoned. CP7 measured
  // exactly that: the frontier offered the branch, the model aimed at it
  // correctly, and nothing could have worked (D-040). It is also realistic: a
  // peer on a socket can send fewer bytes than its header claims.
  //
  uint32_t WireSize = 0;
};

//
// JSON is the on-disk corpus format. Fields are named exactly as the model named
// them, so a corpus is readable against the spec that produced this file.
//
inline void to_json(json::json &Json, const FuzzPacket &Value) {
  Json = json::json{
      {"magic", Value.magic},
      {"total_len", Value.total_len},
      {"payload", Value.payload},
      {"WireSize", Value.WireSize}
  };
}

//
// Optional-with-default rather than at(): nlohmann 3.10.4 has no
// NLOHMANN_DEFINE_TYPE_..._WITH_DEFAULT, and at() on a missing key THROWS --
// which InsertTestcase would catch and skip, silently rejecting every corpus
// entry written before a field was added.
//
inline void from_json(const json::json &Json, FuzzPacket &Value) {
  Value.magic = Json.value("magic", uint32_t(0));
  Value.total_len = Json.value("total_len", uint8_t(0));
  Value.payload = Json.value("payload", std::vector<uint8_t>{});
  Value.WireSize = Json.value("WireSize", uint32_t(0));
}



//
// Residual state we own. The packet queue is ours; guest memory and registers are
// wtf's to restore.
//
struct {
  std::deque<FuzzPacket> Inputs;
  CpuState_t Context;

  void RestoreGprs(Backend_t *B) {
    const auto &C = Context;
    B->Rsp(C.Rsp);
    B->Rip(C.Rip);
    B->Rax(C.Rax);
    B->Rbx(C.Rbx);
    B->Rcx(C.Rcx);
    B->Rdx(C.Rdx);
    B->Rsi(C.Rsi);
    B->Rdi(C.Rdi);
    B->R8(C.R8);
    B->R9(C.R9);
    B->R10(C.R10);
    B->R11(C.R11);
    B->R12(C.R12);
    B->R13(C.R13);
    B->R14(C.R14);
    B->R15(C.R15);
  }
} GlobalState;

//
// Bytes on the wire for one structure, as the target will see it.
//
inline size_t WireSizeOf(const FuzzPacket &Value) {
  return 5 + Value.payload.size();
}

//
// InsertTestcase -- runs on the WORKER.
//
// It does NOT write guest memory here. The test-case is a single structure, and the
// write happens at the entry breakpoint, which is the only place the target is at
// the state the input belongs to.
//
// RETURN VALUE, from src/wtf/client.cc:102-104:
//     if (!Target.InsertTestcase(...)) { print; std::abort(); }
// `false` KILLS THE WORKER. Every rejection of a malformed input therefore
// returns TRUE having done nothing.
//
bool InsertTestcase(const uint8_t *Buffer, const size_t BufferSize) {
  GlobalState.Inputs.clear();

  if (Buffer == nullptr || BufferSize == 0) {
    DebugPrint("empty input, nothing to deliver\n");
    return true;
  }

  try {
    const auto &Root = json::json::parse(Buffer, Buffer + BufferSize);
    GlobalState.Inputs.emplace_back(Root.get<FuzzPacket>());
  } catch (const std::exception &E) {
    DebugPrint("input is not valid JSON ({}), skipping\n", E.what());
    return true;
  }

  //
  // ONE structure per test-case. Written NOW, at the input pointer,
  // because rip is already the entry and a breakpoint there would
  // never fire. Same shape as wtf's own
  // src/wtf/fuzzer_linux_crash_test.cc.
  //
  if (!GlobalState.Inputs.empty()) {
    const auto &Input = GlobalState.Inputs.front();
    uint64_t Address = g_Backend->Rcx();

    if (!g_Backend->VirtWriteStructDirty(Gva_t(Address),
                       &Input.magic)) {
      fmt::print("GenFuzzingTestCmp: failed to write magic\n");
      return true;
    }
    Address += sizeof(Input.magic);

    //
    // Written from the test-case, NOT recomputed from the
    // payload. The disagreement between them is the bug
    // trigger; recomputing here would neuter every overflow.
    //
    if (!g_Backend->VirtWriteStructDirty(Gva_t(Address),
                       &Input.total_len)) {
      fmt::print("GenFuzzingTestCmp: failed to write total_len\n");
      return true;
    }
    Address += sizeof(Input.total_len);

    if (!Input.payload.empty() &&
        !g_Backend->VirtWriteDirty(Gva_t(Address),
                     Input.payload.data(),
                     Input.payload.size())) {
      fmt::print("GenFuzzingTestCmp: failed to write payload\n");
      return true;
    }
  }
  return true;
}

//
// Init -- runs on the WORKER, once.
//


//
// ResolveModuleBase and ResolveInputAddress come from snapfuzz_resolve.h. They used to
// be emitted here, which meant the model-written path had no copy of them and each
// generator could get the arithmetic wrong on its own (D-075).
//
using snapfuzz::ResolveInputAddress;
using snapfuzz::ResolveModuleBase;

bool Init(const Options_t &Opts, const CpuState_t &State) {
  //
  // Resolve the module BEFORE installing anything. Failing here is the difference
  // between an error and a campaign that reports coverage while delivering nothing.
  //
  if (ResolveModuleBase("fuzzing-test-cmp") == 0) {
    return false;
  }


  GlobalState.Context = State;

  const Gva_t Rsp = Gva_t(g_Backend->Rsp());
  const Gva_t ReturnAddress = Gva_t(g_Backend->VirtRead8(Rsp));

  //
  // The fuzz entry. Each hit delivers the next structure; an empty queue ends the
  // test-case.
  //
  if (!g_Backend->SetBreakpoint(Gva_t(ResolveModuleBase("fuzzing-test-cmp") + 0x447c0), [](Backend_t *Backend) {
        if (GlobalState.Inputs.empty()) {
          return Backend->Stop(Ok_t());
        }

        const auto &Input = GlobalState.Inputs.front();
        const size_t Bytes = WireSizeOf(Input);

        //
        // Too big for one page. Drop it and end the test-case -- a Stop(Ok_t()),
        // not a crash and not an abort.
        //
        if (Bytes >= kPageSize || Bytes > kMaxInputBytes) {
          GlobalState.Inputs.pop_front();
          //
          // LOUD, ONCE. "Every test-case is being dropped" is not a debug detail --
          // it is the campaign not running. DebugPrint compiles to nothing
          // (LoggingOn is false), so a harness whose size guard rejected everything
          // reported 0 instructions, no crash and no error: indistinguishable from a
          // clean run. That happened because input_buffer_bytes was 8, read off the
          // size register, and the seed was 21 bytes (D-090).
          //
          static bool DropWarned = false;
          if (!DropWarned) {
            DropWarned = true;
            fmt::print("GenFuzzingTestCmp: DROPPING test-cases -- {} bytes exceeds "
                       "the {}-byte limit from the harness spec.\n"
                       "  Nothing will be delivered at this size. If the target's "
                       "buffer is really larger,\n"
                       "  input_buffer_bytes in harness_spec.json is wrong.\n",
                       Bytes, kMaxInputBytes);
          }
          return Backend->Stop(Ok_t());
        }

        //
        // rdx carries the length, in BYTES.
        //
        // WireSize, when set, reports FEWER (or more) bytes than
        // were written -- modelling a short read on a socket. It is
        // what makes a `size < header` guard reachable at all
        // (D-040).
        //
        size_t Reported = Bytes;
        if (Input.WireSize != 0 && Input.WireSize < kPageSize) {
          Reported = Input.WireSize;
        }
        Backend->Rdx(Reported);

        //
        // rcx HOLDS the buffer address. Slide the write to the tail of the page
        // so the guard page sits immediately behind it.
        //
        // Aligned on the bytes actually WRITTEN, not on any reported size: the
        // guard page must sit behind the real data, or an over-reported size would
        // read our own bytes instead of faulting.
        //
        // Flush against an UNMAPPED page, so a write past the data
        // faults instead of silently landing in mapped memory. The
        // boundary comes from prep/guard_page.py, which walked the
        // dump's page tables to verify it; ResolveInputAddress falls
        // back to the tail of this pointer's own page and says so.
        //
        // This was `PageBase = Backend->Rcx(); PageBase +
        // (kPageSize - Bytes)`, which is wrong twice over: a register
        // holds a POINTER, so without masking the low 12 bits the sum
        // lands PAST the page end, and whether the next page is
        // unmapped was never checked. The model that wrote the other
        // generator was shown this file as its example and reproduced
        // the same mistake.
        uint64_t Address = ResolveInputAddress(Backend->Rcx(), Bytes).U64();
        Backend->Rcx(Address);

        if (!Backend->VirtWriteStructDirty(Gva_t(Address),
                                           &Input.magic)) {
          fmt::print("GenFuzzingTestCmp: failed to write magic\n");
          std::abort();
        }
        Address += sizeof(Input.magic);

        //
        // Written from the test-case, NOT recomputed from the
        // payload. The disagreement between them is the bug
        // trigger; recomputing here would neuter every overflow.
        //
        if (!Backend->VirtWriteStructDirty(Gva_t(Address),
                                           &Input.total_len)) {
          fmt::print("GenFuzzingTestCmp: failed to write total_len\n");
          std::abort();
        }
        Address += sizeof(Input.total_len);

        if (!Input.payload.empty() &&
            !Backend->VirtWriteDirty(Gva_t(Address),
                                     Input.payload.data(),
                                     Input.payload.size())) {
          fmt::print("GenFuzzingTestCmp: failed to write payload\n");
          std::abort();
        }
        GlobalState.Inputs.pop_front();
      })) {
    fmt::print("GenFuzzingTestCmp: failed to SetBreakpoint on {}\n", kFuzzEntry);
    return false;
  }

  //
  // Back at the caller: restore the GPRs so the next structure is delivered from
  // the same state. The snapshot restore does not cover this, because this loops
  // WITHIN one test-case rather than between test-cases (DECISIONS R2).
  //
  // The address is read from the stack rather than named as a symbol: it is a
  // return site, not a function, so there is nothing for dbgeng to resolve.
  //
  //
  // WHERE THE TEST-CASE ENDS, which decides WHICH BUGS THIS HARNESS CAN SEE.
  //
  // `RestoreGprs` rewinds rip to the snapshot, i.e. back to the fuzz entry. That is how a
  // SEQUENCE gets delivered -- return, rewind, deliver the next structure. It also means
  // the CALLER'S EPILOGUE NEVER RUNS, and on a stack-protected binary the epilogue is
  // where `__security_check_cookie` lives. So a harness that rewinds unconditionally
  // cannot observe any stack-cookie violation, no matter how badly the target overflows.
  //
  // Measured on the second real target, whose planted bug overflows the caller's 32-byte
  // buffer:
  //
  //     rewinding:      good  99 instr / cov 53   overflow 124 instr / cov 78   crash 0
  //     running on:     good 283k instr           overflow  3.3k instr         crash 1
  //
  // Same module, same input, same target. The only difference is whether the epilogue was
  // allowed to execute (D-084).
  //
  // So: rewind ONLY when there is another structure to deliver. On the last one, let
  // execution continue -- the crash oracle, `nt!SwapContext` (a clean Cr3Change stop) or
  // `--limit` will end the test-case. Costlier per case, and the cost buys a bug class.
  //
  if (!g_Backend->SetBreakpoint(ReturnAddress, [](Backend_t *Backend) {
        if (GlobalState.Inputs.empty()) {
          DebugPrint("last input delivered; letting the caller's epilogue run\n");
          return;
        }
        GlobalState.RestoreGprs(Backend);
        DebugPrint("back at the entry point, ready for the next input\n");
      })) {
    fmt::print("GenFuzzingTestCmp: failed to SetBreakpoint on the return address\n");
    return false;
  }

  //
  // fuzzing-test-cmp!__CheckForDebuggerJustMyCode: silence_io.
  // Debugger check that may produce side effects or terminate; safe to stub as no-op with zero return to avoid interference.
  //
  if (!g_Backend->SetBreakpoint(Gva_t(ResolveModuleBase("fuzzing-test-cmp") + 0x45094), [](Backend_t *Backend) {
        Backend->SimulateReturnFromFunction(0);
      })) {
    fmt::print("GenFuzzingTestCmp: failed to SetBreakpoint on {}\n", kSkip01);
    return false;
  }

  //
  // THE CRASH ORACLE. wtf infers nothing (section 13.7) -- this installs the
  // platform's user-mode fault hooks (nt!KeBugCheck2, ntdll!RtlDispatchException,
  // verifier!VerifierStopMessage, ...). Each produces a NAMED Crash_t, which
  // matters: the master silently discards a crash whose name is empty
  // (server.h:861-866, D-018).
  //
  // Not derived, and it does not need to be: these fault sites are the same for
  // every Windows target.
  //
  if (!SetupUsermodeCrashDetectionHooks()) {
    fmt::print("GenFuzzingTestCmp: failed to SetupUsermodeCrashDetectionHooks\n");
    return false;
  }

  return true;
}

//
// Per-iteration reset. The snapshot restore handles guest memory and registers; the only residual state here is the input queue, which InsertTestcase clears before each test-case. Restoring twice would be as wrong as not restoring, so this is a no-op (DECISIONS R2).
//
bool Restore() { return true; }

//
// The mutator -- runs on the MASTER (12.1, edge 21a).
//
// If this is not registered the master silently falls back to a built-in mutator
// and every LLM seed is ignored while coverage keeps climbing.
//
class CustomMutator_t : public Mutator_t {
  std::unique_ptr<uint8_t[]> ScratchBuffer__;
  span_u8 ScratchBuffer_;
  size_t TestcaseMaxSize_ = 0;
  std::mt19937_64 &Rng_;
  sfs::path SpoolPath_;
  uint64_t SpoolServed_ = 0;

public:
  //
  // CP10's baseline arms select a BUILT-IN mutator here. wtf has no --mutator
  // flag, so the only way to measure ours against its own is for this factory to
  // hand one back when asked.
  //
  static std::unique_ptr<Mutator_t> Create(std::mt19937_64 &Rng,
                                           const size_t TestcaseMaxSize) {
    if (const char *Env = std::getenv("SNAPFUZZ_MUTATOR"); Env && *Env) {
      const std::string Which(Env);
      if (Which == "libfuzzer") {
        fmt::print("GenFuzzingTestCmp: BASELINE arm -- libfuzzer mutator\n");
        return LibfuzzerMutator_t::Create(Rng, TestcaseMaxSize);
      }
      if (Which == "honggfuzz") {
        fmt::print("GenFuzzingTestCmp: BASELINE arm -- honggfuzz mutator\n");
        return HonggfuzzMutator_t::Create(Rng, TestcaseMaxSize);
      }
      if (Which != "custom") {
        fmt::print("GenFuzzingTestCmp: SNAPFUZZ_MUTATOR={} is not "
                   "libfuzzer/honggfuzz/custom; refusing to guess the arm\n",
                   Which);
        std::fflush(stdout);
        std::abort();
      }
    }
    return std::make_unique<CustomMutator_t>(Rng, TestcaseMaxSize);
  }

  explicit CustomMutator_t(std::mt19937_64 &Rng, const size_t TestcaseMaxSize)
      : Rng_(Rng), TestcaseMaxSize_(TestcaseMaxSize) {
    ScratchBuffer__ = std::make_unique<uint8_t[]>(_1MB);
    ScratchBuffer_ = {ScratchBuffer__.get(), _1MB};
    if (const char *Env = std::getenv(kSpoolEnvVar); Env && *Env) {
      SpoolPath_ = sfs::path(Env);
    }
  }

  std::string GetNewTestcase(const Corpus_t &Corpus) override {
    if (auto Seed = TryTakeSpooledSeed(); Seed.has_value()) {
      SpoolServed_++;
      DebugPrint("served LLM seed #{}\n", SpoolServed_);
      return std::move(*Seed);
    }

    if (GetUint32(1, 5) == 5) {
      return Generate();
    }

    const Testcase_t *Testcase = Corpus.PickTestcase();
    if (!Testcase) {
      return Generate();
    }

    memcpy(ScratchBuffer_.data(), Testcase->Buffer_.get(), Testcase->BufferSize_);
    return Mutate(ScratchBuffer_.data(), Testcase->BufferSize_,
                  ScratchBuffer_.size_bytes());
  }

private:
  //
  // Take at most ONE seed from the spool and delete it.
  //
  // Ownership (RULE 4, DECISIONS R9): the CONSUMER deletes. The sidecar writes
  // atomically (temp then rename) so a half-written seed is never visible, and
  // this end removes the file once it has the bytes. A file that vanishes between
  // listing and reading is another process winning the race, which is fine -- fall
  // through to the built-in mutator this iteration.
  //
  // MUST NOT BLOCK: this runs per test-case on the master with every worker
  // waiting (12.1).
  //
  std::optional<std::string> TryTakeSpooledSeed() {
    if (SpoolPath_.empty()) {
      return std::nullopt;
    }
    std::error_code Ec;
    sfs::directory_iterator It(SpoolPath_, Ec);
    if (Ec) {
      return std::nullopt;
    }
    for (const auto &Entry : It) {
      if (!Entry.is_regular_file(Ec) || Ec) {
        continue;
      }
      const auto &Path = Entry.path();
      if (Path.extension() == ".tmp") {
        continue;
      }
      std::string Content;
      if (!ReadWholeFile(Path, Content)) {
        continue;
      }
      sfs::remove(Path, Ec);
      return Content;
    }
    return std::nullopt;
  }

  static bool ReadWholeFile(const sfs::path &Path, std::string &Out) {
    FILE *File = nullptr;
    if (fopen_s(&File, Path.string().c_str(), "rb") != 0 || File == nullptr) {
      return false;
    }
    char Buffer[4096];
    size_t Read = 0;
    Out.clear();
    while ((Read = fread(Buffer, 1, sizeof(Buffer), File)) > 0) {
      Out.append(Buffer, Read);
    }
    fclose(File);
    return !Out.empty();
  }

  uint32_t GetUint32(const uint32_t Min, const uint32_t Max) {
    return Min + uint32_t(Rng_() % (uint64_t(Max) - Min + 1));
  }

  //
  // Generate from scratch, field by field, per the derived spec.
  //
  // Length fields are made CONSISTENT here: an input whose length disagrees with
  // its payload is rejected at the parser's first check, and a corpus of rejected
  // inputs teaches the fuzzer nothing (CP4). Mutate is where they are allowed to
  // disagree, because that disagreement is the bug.
  //
  std::string Generate() {
    FuzzPacket Root;
        FuzzPacket Item;
        // The parser compares this against a constant, so a random
      // value is rejected immediately. Kept correct MOST of the
      // time so the corpus gets past the check at all.
      Item.magic = GetUint32(1, 10) == 1
                              ? uint32_t(GetUint32(0, 0xffff))
                              : uint32_t(0x5a5a5546);
        // Consistent with the payload: an inconsistent length is
      // rejected at the parser's first check, and a corpus of
      // rejected inputs teaches the fuzzer nothing (CP4).
      Item.total_len = uint8_t(Item.payload.size());
        const uint32_t Len = GetUint32(0, 255);
        Item.payload.resize(Len);
        for (uint32_t I = 0; I < Len; I++) {
          Item.payload[I] = uint8_t(GetUint32(0, 255));
        }
        // Usually the natural size; occasionally a lie, which is the
      // only way a `size < header` guard is reachable (D-040).
      Item.WireSize = GetUint32(1, 8) == 1 ? GetUint32(0, 8) : 0;
    Root = Item;
    json::json Serialized;
    to_json(Serialized, Root);
    return Serialized.dump();
  }

  std::string Mutate(uint8_t *Data, const size_t DataLen, const size_t MaxSize) {
    FuzzPacket Root;
    try {
      const auto &Parsed = json::json::parse(Data, Data + DataLen);
      Root = Parsed.get<FuzzPacket>();
    } catch (const std::exception &) {
      // Not our format -- start fresh rather than aborting the master.
      return Generate();
    }
    std::vector<FuzzPacket> Items{Root};
    if (Items.empty()) {
      return Generate();
    }

    const size_t Index = GetUint32(0, uint32_t(Items.size() - 1));
    auto &Item = Items[Index];

    switch (GetUint32(0, 5)) {
    case 0:
      // Flip a header field. Length fields included ON PURPOSE: a
      // length that disagrees with the payload is the bug.
      switch (GetUint32(0, 1)) {
      case 0:
        Item.magic = uint32_t(GetUint32(0, 0xffff));
        break;
      case 1:
        Item.total_len = uint8_t(GetUint32(0, 0xffff));
        break;
      }
      break;
    case 1: {
      // Grow the payload without touching the declared length.
      const uint32_t Extra = GetUint32(1, 64);
      for (uint32_t I = 0; I < Extra; I++) {
        Item.payload.push_back(uint8_t(GetUint32(0, 255)));
      }
      break;
    }
    case 2:
      // Shrink it, likewise leaving the length alone.
      if (!Item.payload.empty()) {
        Item.payload.resize(Item.payload.size() / 2);
      }
      break;
    case 3:
      if (!Item.payload.empty()) {
        Item.payload[GetUint32(0, uint32_t(Item.payload.size() - 1))] =
            uint8_t(GetUint32(0, 255));
      }
      break;
    default:
      Item.WireSize = GetUint32(0, 16);
      break;
    }
    Root = Items[0];
    json::json Serialized;
    to_json(Serialized, Root);
    std::string Out = Serialized.dump();
    if (Out.size() > MaxSize) {
      return Generate();
    }
    return Out;
  }
};

} // namespace GenFuzzingTestCmp

//
// The registration. ONE artifact, loaded by the master (which uses
// CustomMutator_t) and every worker (which uses Init / InsertTestcase / Restore).
// Both roles, one module (edges 21a and 21b).
//
Target_t GenFuzzingTestCmpTarget("snapfuzz_gen", GenFuzzingTestCmp::Init,
                      GenFuzzingTestCmp::InsertTestcase, GenFuzzingTestCmp::Restore,
                      GenFuzzingTestCmp::CustomMutator_t::Create);
